[package]
name = "emergency-deployment"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-openssl = "0.6"
openssl = { version = "0.10", features = ["vendored"] }
dotenv = "0.15"
chrono = "0.4"

